export const courseData = {
    chapters: [
      {
        id: 1,
        title: "Introduction to Programming",
        totalTime: "03:30:00",
        parts: [
          {
            id: 1,
            title: "Basic Concepts",
            time: "01:00:00",
            level: "Easy",
            modules: 5,
            completedModules: 3,
            content: ["Video 1", "Article 1", "Quiz 1", "Coding Exercise 1", "Combined Resource"],
          },
          {
            id: 2,
            title: "Variables & Data Types",
            time: "01:30:00",
            level: "Medium",
            modules: 4,
            completedModules: 2,
            content: ["Video 1", "Coding Exercise 1"],
          },
          {
            id: 3,
            title: "Control Structures",
            time: "01:00:00",
            level: "Medium",
            modules: 3,
            completedModules: 1,
            content: ["Video 1", "Quiz 1"],
          },
        ],
      },
      {
        id: 2,
        title: "Object-Oriented Programming",
        totalTime: "04:00:00",
        parts: [
          {
            id: 1,
            title: "Classes & Objects",
            time: "01:00:00",
            level: "Medium",
            modules: 4,
            completedModules: 2,
            content: ["Video 1", "Article 1", "Combined Resource"],
          },
          {
            id: 2,
            title: "Inheritance",
            time: "01:00:00",
            level: "Hard",
            modules: 3,
            completedModules: 1,
            content: ["Video 1", "Quiz 1"],
          },
          {
            id: 3,
            title: "Polymorphism",
            time: "01:00:00",
            level: "Hard",
            modules: 4,
            completedModules: 0,
            content: ["Video 1", "Coding Exercise 1", "Combined Resource"],
          },
          {
            id: 4,
            title: "Encapsulation",
            time: "01:00:00",
            level: "Medium",
            modules: 3,
            completedModules: 0,
            content: ["Video 1", "Quiz 1"],
          },
        ],
      },
      {
        id: 3,
        title: "Data Structures",
        totalTime: "03:45:00",
        parts: [
          {
            id: 1,
            title: "Arrays & Lists",
            time: "01:15:00",
            level: "Medium",
            modules: 4,
            completedModules: 2,
            content: ["Video 1", "Quiz 1", "Coding Exercise 1", "Combined Resource"],
          },
          {
            id: 2,
            title: "Stacks & Queues",
            time: "01:15:00",
            level: "Hard",
            modules: 3,
            completedModules: 1,
            content: ["Video 1", "Quiz 1"],
          },
          {
            id: 3,
            title: "Trees & Graphs",
            time: "01:15:00",
            level: "Hard",
            modules: 5,
            completedModules: 2,
            content: ["Video 1", "Coding Exercise 1", "Combined Resource"],
          },
        ],
      },
      {
        id: 4,
        title: "Algorithms",
        totalTime: "04:30:00",
        parts: [
          {
            id: 1,
            title: "Sorting Algorithms",
            time: "01:00:00",
            level: "Medium",
            modules: 4,
            completedModules: 3,
            content: ["Video 1", "Article 1", "Quiz 1"],
          },
          {
            id: 2,
            title: "Searching Algorithms",
            time: "01:00:00",
            level: "Medium",
            modules: 4,
            completedModules: 2,
            content: ["Video 1", "Combined Resource", "Coding Exercise 1"],
          },
          {
            id: 3,
            title: "Dynamic Programming",
            time: "01:30:00",
            level: "Hard",
            modules: 5,
            completedModules: 1,
            content: ["Video 1", "Quiz 1"],
          },
          {
            id: 4,
            title: "Greedy Algorithms",
            time: "01:00:00",
            level: "Medium",
            modules: 3,
            completedModules: 1,
            content: ["Video 1", "Coding Exercise 1"],
          },
        ],
      },
      {
        id: 5,
        title: "Databases",
        totalTime: "03:30:00",
        parts: [
          {
            id: 1,
            title: "Introduction to Databases",
            time: "00:45:00",
            level: "Easy",
            modules: 3,
            completedModules: 2,
            content: ["Video 1", "Article 1", "Combined Resource"],
          },
          {
            id: 2,
            title: "SQL Basics",
            time: "01:15:00",
            level: "Medium",
            modules: 5,
            completedModules: 3,
            content: ["Video 1", "Quiz 1", "Coding Exercise 1"],
          },
          {
            id: 3,
            title: "NoSQL Databases",
            time: "01:00:00",
            level: "Medium",
            modules: 4,
            completedModules: 1,
            content: ["Video 1", "Article 1"],
          },
          {
            id: 4,
            title: "Database Security",
            time: "00:30:00",
            level: "Hard",
            modules: 2,
            completedModules: 0,
            content: ["Video 1", "Quiz 1"],
          },
        ],
      },
    ],
  };
  